(function () {
  'use strict';

    /*global app:true*/

  var title = 'Que trata de la condici&oacute;n y ejercicio del famoso hidalgo D. Quijote de la Mancha';

  var chapter = [];

  chapter.push('En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho tiempo que viv&iacute;a un hidalgo de los de lanza en astillero, adarga antigua, roc&iacute;n flaco y galgo corredor. Una olla de algo m&aacute;s vaca que carnero, salpic&oacute;n las m&aacute;s noches, duelos y quebrantos los s&aacute;bados, lentejas los viernes, alg&uacute;n palomino de a&ntilde;adidura los domingos, consum&iacute;an las tres partes de su hacienda. El resto della conclu&iacute;an sayo de velarte, calzas de velludo para las fiestas con sus pantuflos de lo mismo, los d&iacute;as de entre semana se honraba con su vellori de lo m&aacute;s fino. Ten&iacute;a en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza, que as&iacute; ensillaba el roc&iacute;n como tomaba la podadera. Frisaba la edad de nuestro hidalgo con los cincuenta a&ntilde;os, era de complexi&oacute;n recia, seco de carnes, enjuto de rostro; gran madrugador y amigo de la caza. Quieren decir que ten&iacute;a el sobrenombre de Quijada o Quesada (que en esto hay alguna diferencia en los autores que deste caso escriben), aunque por conjeturas veros&iacute;miles se deja entender que se llama Quijana; pero esto importa poco a nuestro cuento; basta que en la narraci&oacute;n d&eacute;l no se salga un punto de la verdad.');

  chapter.push('Es, pues, de saber, que este sobredicho hidalgo, los ratos que estaba ocioso (que eran los m&aacute;s del a&ntilde;o) se daba a leer libros de caballer&iacute;as con tanta afici&oacute;n y gusto, que olvid&oacute; casi de todo punto el ejercicio de la caza, y aun la administraci&oacute;n de su hacienda; y lleg&oacute; a tanto su curiosidad y desatino en esto, que vendi&oacute; muchas hanegas de tierra de sembradura, para comprar libros de caballer&iacute;as en que leer; y as&iacute; llev&oacute; a su casa todos cuantos pudo haber dellos; y de todos ningunos le parec&iacute;an tan bien como los que compuso el famoso Feliciano de Silva: porque la claridad de su prosa, y aquellas intrincadas razones suyas, le parec&iacute;an de perlas; y m&aacute;s cuando llegaba a leer aquellos requiebros y cartas de desaf&iacute;o, donde en muchas partes hallaba escrito: la raz&oacute;n de la sinraz&oacute;n que a mi raz&oacute;n se hace, de tal manera mi raz&oacute;n enflaquece, que con raz&oacute;n me quejo de la vuestra fermosura, y tambi&eacute;n cuando le&iacute;a: los altos cielos que de vuestra divinidad divinamente con las estrellas se fortifican, y os hacen merecedora del merecimiento que merece la vuestra grandeza. Con estas y semejantes razones perd&iacute;a el pobre caballero el juicio, y desvel&aacute;base por entenderlas, y desentra&ntilde;arles el sentido, que no se lo sacara, ni las entendiera el mismo Arist&oacute;teles, si resucitara para s&oacute;lo ello. No estaba muy bien con las heridas que don Belianis daba y recib&iacute;a, porque se imaginaba que por grandes maestros que le hubiesen curado, no dejar&iacute;a de tener el rostro y todo el cuerpo lleno de cicatrices y se&ntilde;ales; pero con todo alababa en su autor aquel acabar su libro con la promesa de aquella inacabable aventura, y muchas veces le vino deseo de tomar la pluma, y darle fin al pie de la letra como all&iacute; se promete; y sin duda alguna lo hiciera, y aun saliera con ello, si otros mayores y continuos pensamientos no se lo estorbaran.');

  chapter.push('Tuvo muchas veces competencia con el cura de su lugar (que era hombre docto graduado en Sig&uuml;enza), sobre cu&aacute;l hab&iacute;a sido mejor caballero, Palmer&iacute;n de Inglaterra o Amad&iacute;s de Gaula; mas maese Nicol&aacute;s, barbero del mismo pueblo, dec&iacute;a que ninguno llegaba al caballero del Febo, y que si alguno se le pod&iacute;a comparar, era don Galaor, hermano de Amad&iacute;s de Gaula, porque ten&iacute;a muy acomodada condici&oacute;n para todo; que no era caballero melindroso, ni tan llor&oacute;n como su hermano, y que en lo de la valent&iacute;a no le iba en zaga.');

  chapter.push('En resoluci&oacute;n, &eacute;l se enfrasc&oacute; tanto en su lectura, que se le pasaban las noches leyendo de claro en claro, y los d&iacute;as de turbio en turbio, y as&iacute;, del poco dormir y del mucho leer, se le sec&oacute; el cerebro, de manera que vino a perder el juicio. Llen&oacute;sele la fantas&iacute;a de todo aquello que le&iacute;a en los libros, as&iacute; de encantamientos, como de pendencias, batallas, desaf&iacute;os, heridas, requiebros, amores, tormentas y disparates imposibles, y asent&oacute;sele de tal modo en la imaginaci&oacute;n que era verdad toda aquella m&aacute;quina de aquellas so&ntilde;adas invenciones que le&iacute;a, que para &eacute;l no hab&iacute;a otra historia m&aacute;s cierta en el mundo.');

  chapter.push('Dec&iacute;a &eacute;l, que el Cid Ruy D&iacute;az hab&iacute;a sido muy buen caballero; pero que no ten&iacute;a que ver con el caballero de la ardiente espada, que de s&oacute;lo un rev&eacute;s hab&iacute;a partido por medio dos fieros y descomunales gigantes. Mejor estaba con Bernardo del Carpio, porque en Roncesvalle hab&iacute;a muerto a Rold&aacute;n el encantado, vali&eacute;ndose de la industria de H&eacute;rcules, cuando ahog&oacute; a Anteo, el hijo de la Tierra, entre los brazos. Dec&iacute;a mucho bien del gigante Morgante, porque con ser de aquella generaci&oacute;n gigantesca, que todos son soberbios y descomedidos, &eacute;l solo era afable y bien criado; pero sobre todos estaba bien con Reinaldos de Montalb&aacute;n, y m&aacute;s cuando le ve&iacute;a salir de su castillo y robar cuantos topaba, y cuando en Allende rob&oacute; aquel &iacute;dolo de Mahoma, que era todo de oro, seg&uacute;n dice su historia. Diera &eacute;l, por dar una mano de coces al traidor de Galal&oacute;n, al ama que ten&iacute;a y aun a su sobrina de a&ntilde;adidura.');

  var book = app.book['quijote'];
  book.push({ key: 1, title: title, value: chapter });

}());