(function () {
  'use strict';

    /*global app:true*/

  var title = 'Que trata de la primera salida que de su tierra hizo el ingenioso D. Quijote';

  var chapter = [];

  chapter.push('Hechas, pues, estas prevenciones, no quiso aguardar m&aacute;s tiempo a poner en efecto su pensamiento, apret&aacute;ndole a ello la falta que &eacute;l pensaba que hac&iacute;a en el mundo su tardanza, seg&uacute;n eran los agravios que pensaba deshacer, tuertos que enderezar, sinrazones que enmendar, y abusos que mejorar, y deudas que satisfacer; y as&iacute;, sin dar parte a persona alguna de su intenci&oacute;n, y sin que nadie le viese, una mañana, antes del d&iacute;a (que era uno de los calurosos del mes de Julio), se arm&oacute; de todas sus armas, subi&oacute; sobre Rocinante, puesta su mal compuesta celada, embraz&oacute; su adarga, tom&oacute; su lanza, y por la puerta falsa de un corral, sali&oacute; al campo con grand&iacute;simo contento y alborozo de ver con cu&aacute;nta facilidad hab&iacute;a dado principio a su buen deseo. Mas apenas se vi&oacute; en el campo, cuando le asalt&oacute; un pensamiento terrible, y tal, que por poco le hiciera dejar la comenzada empresa: y fue que le vino a la memoria que no era armado caballero, y que, conforme a la ley de caballer&iacute;a, ni pod&iacute;a ni deb&iacute;a tomar armas con ning&uacute;n caballero; y puesto qeu lo fuera, hab&iacute;a de llevar armas blancas, como novel caballero, sin empresa en el escudo, hasta que por su esfuerzo la ganase.');

  chapter.push('Estos pensamientos le hicieron titubear en su prop&oacute;sito; mas pudiendo m&aacute;s su locura que otra raz&oacute;n alguna, propuso de hacerse armar caballero del primero que topase, a imitaci&oacute;n de otros muchos que as&iacute; lo hicieron, seg&uacute;n &eacute;l hab&iacute;a le&iacute;do en los libros que tal le ten&iacute;an. En lo de las armas blancas pensaba limpiarlas de manera, en teniendo lugar, que lo fuesen m&aacute;s que un armiño: y con esto se quiet&oacute; y prosigui&oacute; su camino, sin llevar otro que el que su caballo quer&iacute;a, creyendo que en aquello consist&iacute;a la fuerza de las aventuras. Yendo, pues, caminando nuestro flamante aventurero, iba hablando consigo mismo, y diciendo: ¿Qui&eacute;n duda sino que en los venideros tiempos, ciando salga a luz la verdadera historia de mis famosos hechos, que el sabio que los escribiere, no ponga, cuando llegue a contar esta mi primera salida tan de mañana, de esta manera? "Apenas hab&iacute;a el rubicundo Apolo tendido por la faz de la ancha y espaciosa tierra las doradas hebras de sus hermosos cabellos, y apenas los pequeños y pintados pajarillos con sus arpadas lenguas hab&iacute;an saludado con dulce y meliflua armon&iacute;a la venida de la rosada aurora que dejando la blanda cama del celoso marido, por las puertas y balcones del manchego horizonte a los mortales se mostraba, cuando el famoso caballero D. Quijote de la Mancha, dejando las ociosas plumas, subi&oacute; sobre su famoso caballo Rocinante, y comenz&oacute; a caminar por el antiguo y conocido campo de Montiel." (Y era la verdad que por &eacute;l caminaba) y añadi&oacute; diciendo: "dichosa edad, y siglo dichoso aquel adonde saldr&aacute;n a luz las famosas hazañas m&iacute;as, dignas de entallarse en bronce, esculpirse en m&aacute;rmoles y esculpirse en m&aacute;rmoles y pintarse en tablas para memoria en lo futuro. ¡Oh t&uacute;, sabio encantador, quienquiera que seas, a quien ha de tocar el ser coronista de esta peregrina historia! Ru&eacute;gote que no te olvides de mi buen Rocinante compañero eterno m&iacute;o en todos mis caminos y carreras." Luego volv&iacute;a diciendo, como si verdaderamente fuera enamorado: "¡Oh, princesa Dulcinea, señora de este cautivo coraz&oacute;n! Mucho agravio me habedes fecho en despedirme y reprocharme con el riguroso afincamiento de mandarme no parecer ante la vuestra fermosura. Pl&eacute;gaos, señora, de membraros de este vuestro sujeto coraz&oacute;n, que tantas cuitas por vuestro amor padece." ');

  chapter.push('Con estos iba ensartando otros disparates, todos al modo de los que sus libros le hab&iacute;an enseñado, imitando en cuanto pod&iacute;a su lenguaje; y con esto caminaba tan despaico, y el sol entraba tan apriesa y con tanto ardor, que fuera bastante a derretirle los sesos, si algunos tuviera. Casi todo aquel d&iacute;a camin&oacute; sin acontecerle cosa que de contar fuese, de lo cual se desesperaba, poerque quisiera topar luego, con quien hacer experiencia del valor de su fuerte brazo. ');

  chapter.push('Autores hay que dicen que la primera aventura que le avino fue la de Puerto L&aacute;pice; otros dicen que la de los molinos de viento; pero lo que yo he podido averiguar en este caso, y lo que he hallado escrito en los anales de la Mancha, es que &eacute;l anduvo todo aquel d&iacute;a, y al anochecer, su roc&iacute;n y &eacute;l se hallaron cansados y muertos de hambre; y que mirando a todas partes, por ver si descubrir&iacute;a alg&uacute;n castillo o alguna majada de pastores donde recogerse, y adonde pudiese remediar su mucha necesidad, vi&oacute; no lejos del camino por donde iba una venta, que fue como si viera una estrella, que a los portales, si no a los alc&aacute;zares de su redenci&oacute;n, le encaminaba. Di&oacute;se priesa a caminar, y lleg&oacute; a ella a tiempo que anochec&iacute;a. Estaban acaso a la puerta dos mujeres mozas, de estas que llaman del partido, las cuales iban a Sevilla con unos arrieros, que en la venta aquella noche acertaron a hacer jornada; y como a nuestro aventurero todo cuanto pensaba, ve&iacute;a o imaginaba, le parec&iacute;a ser hecho y pasar al modo de lo que hab&iacute;a le&iacute;do, luego que vi&oacute; la venta se le represent&oacute; que era un castillo con sus cuatro torres y chapiteles de luciente plata, sin faltarle su puente levadizo y honda cava, con todos aquellos adherentes que semejantes castillos se pintan.');

  var book = app.book['quijote'];
  book.push({ key: 2, title: title, value: chapter });

}());